# Generated by Django 3.2.4 on 2021-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khistory',
            name='adjust_flag',
            field=models.SmallIntegerField(choices=[(1, '后复权'), (2, '前复权'), (3, '不复权')], default=1, verbose_name='复权状态'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='is_st',
            field=models.SmallIntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='复权状态'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='trades_tatus',
            field=models.SmallIntegerField(choices=[(1, '正常交易'), (0, '停牌')], default=1, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ipo_status',
            field=models.SmallIntegerField(choices=[(1, '上市'), (0, '退市')], default=1, verbose_name='上市状态'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ipo_type',
            field=models.SmallIntegerField(choices=[(1, '股票'), (2, '指数'), (3, '其它')], default=1, verbose_name='证券类型'),
        ),
    ]
