# Generated by Django 3.2.4 on 2021-06-27 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210614_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='khistory',
            name='avgPE',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='近十年滚动市盈率'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='is_st',
            field=models.SmallIntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否ST'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='证券名称'),
        ),
    ]
