# Generated by Django 3.2.4 on 2021-06-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20210627_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khistory',
            name='close_price',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='今收盘价'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='high_price',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='low_price',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='maxPE',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='近十年最高市盈率'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='minPE',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='近十年最低市盈率'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='open_price',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='今开盘价格'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='pbMRQ',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='市净率'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='pcfNcfTTM',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='滚动市现率'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='pctChg',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='涨跌幅（百分比）'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='peTTM',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='滚动市盈率'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='preclose_price',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='昨日收盘价'),
        ),
        migrations.AlterField(
            model_name='khistory',
            name='psTTM',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='滚动市销率'),
        ),
    ]
