# Generated by Django 3.2.4 on 2021-08-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stock_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='规则名称')),
                ('operation', models.SmallIntegerField(choices=[(2, '高估操作（卖出）'), (1, '低估操作（买进）')], default=1, verbose_name='高估 or 低估')),
                ('limit', models.SmallIntegerField(default=1, verbose_name='高低估区间，PE Range 上限值，单位%')),
                ('holding', models.SmallIntegerField(default=1, verbose_name='股票持仓比例，单位%')),
                ('available', models.SmallIntegerField(choices=[(1, '生效中'), (0, '无效')], default=0, verbose_name='是否生效')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('priority', models.SmallIntegerField(default=1, verbose_name='优先级')),
            ],
            options={
                'verbose_name': '规则',
                'verbose_name_plural': '所有规则',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='策略名称')),
                ('available', models.SmallIntegerField(choices=[(1, '生效中'), (0, '无效')], default=0, verbose_name='是否生效')),
                ('top_limit', models.SmallIntegerField(default=1, verbose_name='高估区间，PE Range 上限值，单位%')),
                ('bottom_limit', models.SmallIntegerField(default=1, verbose_name='低估区间，PE Range 下限值，单位%')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('calculated_date', models.DateTimeField(verbose_name='运算时间')),
                ('status', models.SmallIntegerField(choices=[(2, '运算完毕'), (1, '运算中'), (0, '新创建')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '策略',
                'verbose_name_plural': '所有策略',
            },
        ),
        migrations.AddField(
            model_name='khistory',
            name='avgPE',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True, verbose_name='近十年平均市盈率'),
        ),
    ]
