# Generated by Django 3.2.4 on 2021-08-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20210823_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='strategy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stocks.strategy', verbose_name='策略名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='available',
            field=models.SmallIntegerField(choices=[(1, '生效中'), (0, '无效')], default=1, verbose_name='是否生效'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='available',
            field=models.SmallIntegerField(choices=[(1, '生效中'), (0, '无效')], default=1, verbose_name='是否生效'),
        ),
    ]
