# Generated by Django 3.2.4 on 2021-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20210823_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='calculated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='运算时间'),
        ),
    ]
