# Generated by Django 3.2.4 on 2021-09-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_strategy_calculated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='s_type',
            field=models.SmallIntegerField(choices=[(1, 'MM策略'), (2, '均值策略')], default=1, verbose_name='策略类型'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='stocks',
            field=models.ManyToManyField(related_name='strategy_stocks', to='stocks.Stock', verbose_name='选择策略应用于的股票/指数（可以多选）'),
        ),
    ]
