# Generated by Django 3.2.4 on 2021-09-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_auto_20210907_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khistory',
            name='avgMaxPE',
        ),
        migrations.RemoveField(
            model_name='khistory',
            name='avgMinPE',
        ),
        migrations.RemoveField(
            model_name='khistory',
            name='avgPE',
        ),
        migrations.RemoveField(
            model_name='khistory',
            name='maxPE',
        ),
        migrations.RemoveField(
            model_name='khistory',
            name='minPE',
        ),
        migrations.AddField(
            model_name='khistory',
            name='metrics_value',
            field=models.TextField(blank=True, null=True, verbose_name='PE自动计算值'),
        ),
    ]
