# Generated by Django 3.2.5 on 2021-10-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_auto_20210917_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='s_type',
            field=models.SmallIntegerField(choices=[(1, 'MM策略'), (2, '均值策略'), (3, '均值策略V1')], default=1, verbose_name='策略类型'),
        ),
    ]
