# Generated by Django 3.2.5 on 2021-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_alter_strategy_s_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='object_fund',
            field=models.TextField(blank=True, null=True, verbose_name='可操作基金'),
        ),
    ]
